Repository HW-WANT-PROJECT/want_project, pull requests merged in 2024-07, with the labels that each got.

#1 BlockCreate, Block List, BlockDetail
  build.gradle
  src/main/java/com/example/want/block/controller/BlockController.java
  src/main/java/com/example/want/block/domain/Block.java
  src/main/java/com/example/want/block/dto/BlockActiveListRsDto.java
  src/main/java/com/example/want/block/dto/BlockDetailRsDto.java
  src/main/java/com/example/want/block/dto/CreatBlockRqDto.java
  src/main/java/com/example/want/block/repository/BlockRepository.java
  src/main/java/com/example/want/block/service/BlockService.java
  src/main/java/com/example/want/common/BaseEntity.java
  src/main/java/com/example/want/common/CommonErrorDto.java
  src/main/java/com/example/want/common/CommonResDto.java
  src/main/resources/application.yml
Labels: ⭐️ Feat

#2 브랜치 이름 잘못만들어서 다시 생성합니다.
  build.gradle
  src/main/java/com/example/want/block/controller/BlockController.java
  src/main/java/com/example/want/block/domain/Block.java
  src/main/java/com/example/want/block/dto/BlockActiveListRsDto.java
  src/main/java/com/example/want/block/dto/BlockDetailRsDto.java
  src/main/java/com/example/want/block/dto/CreatBlockRqDto.java
  src/main/java/com/example/want/block/repository/BlockRepository.java
  src/main/java/com/example/want/block/service/BlockService.java
  src/main/java/com/example/want/common/BaseEntity.java
  src/main/java/com/example/want/common/CommonErrorDto.java
  src/main/java/com/example/want/common/CommonResDto.java
  src/main/resources/application.yml
Labels: ⚙️ setting

#3 [Setting]
  src/main/java/com/example/want/api/block/controller/BlockController.java
  src/main/java/com/example/want/api/block/domain/Block.java
  src/main/java/com/example/want/api/block/dto/BlockActiveListRsDto.java
  src/main/java/com/example/want/api/block/dto/BlockDetailRsDto.java
  src/main/java/com/example/want/api/block/dto/CreatBlockRqDto.java
  src/main/java/com/example/want/api/block/repository/BlockRepository.java
  src/main/java/com/example/want/api/block/service/BlockService.java
  src/main/java/com/example/want/api/user/controller/MemberController.java
  src/main/java/com/example/want/api/user/domain/Member.java
  src/main/java/com/example/want/api/user/domain/Role.java
  src/main/java/com/example/want/api/user/repository/MemberRepository.java
  src/main/java/com/example/want/block/controller/BlockController.java
  src/main/java/com/example/want/common/CommonExceptionHandler.java
  src/main/java/com/example/want/config/SwaggerConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ⚙️ setting

#5 좋아요 Redis를 사용하여 +1, -1 , 좋아요 조회
  build.gradle
  src/main/java/com/example/want/api/block/controller/BlockController.java
  src/main/java/com/example/want/api/block/domain/Block.java
  src/main/java/com/example/want/api/block/dto/BlockDetailRsDto.java
  src/main/java/com/example/want/api/block/dto/CreatBlockRqDto.java
  src/main/java/com/example/want/api/block/service/BlockService.java
  src/main/java/com/example/want/api/heart/domain/Heart.java
  src/main/java/com/example/want/api/heart/repository/HeartRepository.java
  src/main/java/com/example/want/api/user/domain/Role.java
  src/main/java/com/example/want/config/RedisConfig.java
  src/main/resources/application-local.yml
Labels: ⭐️ Feat

#6 블록 리스트 조회 수정, 활성화 되어있는지 아닌지, 좋아요 순으로 정렬, 시작 시간 순으로 정렬
  src/main/java/com/example/want/api/block/dto/BlockActiveListRsDto.java
  src/main/java/com/example/want/api/block/repository/BlockRepository.java
  src/main/java/com/example/want/api/block/service/BlockService.java
Labels: Fix

#11 구글 로그인 추가
  build.gradle
  src/main/java/com/example/want/api/block/controller/BlockController.java
  src/main/java/com/example/want/api/block/domain/Block.java
  src/main/java/com/example/want/api/block/dto/BlockActiveListRsDto.java
  src/main/java/com/example/want/api/block/repository/BlockRepository.java
  src/main/java/com/example/want/api/block/service/BlockService.java
  src/main/java/com/example/want/api/block_comment/dto/CreateCmtRqDto.java
  src/main/java/com/example/want/api/block_comment/entity/Cmt.java
  src/main/java/com/example/want/api/block_comment/service/CmtService.java
  src/main/java/com/example/want/api/heart/domain/Heart.java
  src/main/java/com/example/want/api/heart/repository/HeartRepository.java
  src/main/java/com/example/want/api/member/controller/AuthController.java
  src/main/java/com/example/want/api/member/controller/MemberController.java
  src/main/java/com/example/want/api/member/domain/Member.java
  src/main/java/com/example/want/api/member/domain/Role.java
  src/main/java/com/example/want/api/member/dto/LoginRqDto.java
  src/main/java/com/example/want/api/member/dto/LoginRsDto.java
  src/main/java/com/example/want/api/member/dto/MemberCreateRqDto.java
  src/main/java/com/example/want/api/member/login/SecurityConfig.java
  src/main/java/com/example/want/api/member/login/UserInfo.java
  src/main/java/com/example/want/api/member/login/dto/GoogleLoginRqDto.java
  src/main/java/com/example/want/api/member/login/jwt/JwtFilter.java
  src/main/java/com/example/want/api/member/login/jwt/JwtTokenProvider.java
  src/main/java/com/example/want/api/member/login/jwt/TokenProvider.java
  src/main/java/com/example/want/api/member/login/jwt/TokenResponse.java
  src/main/java/com/example/want/api/member/login/oauth/GoogleOAuth2UserInfo.java
  src/main/java/com/example/want/api/member/login/oauth/OAuth2UserInfo.java
  src/main/java/com/example/want/api/member/repository/MemberRepository.java
  src/main/java/com/example/want/api/member/service/AuthService.java
  src/main/java/com/example/want/api/member/service/MemberService.java
  src/main/java/com/example/want/api/project/domain/Project.java
  src/main/java/com/example/want/api/project/dto/ProjectDetailResDto.java
  src/main/java/com/example/want/api/project/service/ProjectService.java
  src/main/java/com/example/want/api/traveluser/domain/TravelUser.java
  src/main/java/com/example/want/api/user/controller/MemberController.java
  src/main/java/com/example/want/api/user/domain/Member.java
  src/main/java/com/example/want/config/SwaggerConfig.java
  src/main/resources/application-local.yml
Labels: ⭐️ Feat

#8 좋아요 순 블록 조회 / 날짜별 일정 조회
  build.gradle
  src/main/java/com/example/want/api/block/controller/BlockController.java
  src/main/java/com/example/want/api/block/domain/Block.java
  src/main/java/com/example/want/api/block/domain/Category.java
  src/main/java/com/example/want/api/block/dto/AddDateBlockRqDto.java
  src/main/java/com/example/want/api/block/dto/BlockByDateRsDto.java
  src/main/java/com/example/want/api/block/dto/BlockDetailRsDto.java
  src/main/java/com/example/want/api/block/dto/BlockExtractDateRqDto.java
  src/main/java/com/example/want/api/block/dto/CreateBlockRqDto.java
  src/main/java/com/example/want/api/block/repository/BlockRepository.java
  src/main/java/com/example/want/api/block/service/BlockService.java
  src/main/java/com/example/want/api/heart/dto/HeartListResDto.java
  src/main/java/com/example/want/common/BaseEntity.java
  src/main/resources/application-local.yml
Labels: ⭐️ Feat

#13 관리자용 장소 지역 테이블 생성
  src/main/java/com/example/want/api/state/domain/Location.java
  src/main/java/com/example/want/api/state/domain/ProjectState.java
  src/main/java/com/example/want/api/state/domain/State.java
Labels: ⭐️ Feat

#15 내가속한 활성화된 프로젝트 리스트 출력
  src/main/java/com/example/want/api/member/repository/MemberRepository.java
  src/main/java/com/example/want/api/project/controller/ProjectController.java
  src/main/java/com/example/want/api/project/dto/MyProjectListRsDto.java
  src/main/java/com/example/want/api/project/service/ProjectService.java
  src/main/java/com/example/want/api/traveluser/Repository/TravelUserRepository.java
Labels: ⭐️ Feat

#22 TravelUser 테이블 이름 변경 및 project create 코드 수정
  src/main/java/com/example/want/api/project/controller/ProjectController.java
  src/main/java/com/example/want/api/project/domain/Project.java
  src/main/java/com/example/want/api/project/dto/MyProjectListRsDto.java
  src/main/java/com/example/want/api/project/dto/ProjectCreateReqDto.java
  src/main/java/com/example/want/api/project/service/ProjectService.java
  src/main/java/com/example/want/api/projectMember/Repository/ProjectMemberRepository.java
  src/main/java/com/example/want/api/projectMember/domain/ProjectMember.java
  src/main/java/com/example/want/api/traveluser/dto/LeaderDto.java
Labels: ⭐️ Feat, Fix

#21 Block creator 삭제 및 block 의 각종 수정기능 추가
  src/main/java/com/example/want/api/block/controller/BlockController.java
  src/main/java/com/example/want/api/block/domain/Block.java
  src/main/java/com/example/want/api/block/domain/Category.java
  src/main/java/com/example/want/api/block/dto/CreateBlockRqDto.java
  src/main/java/com/example/want/api/block/dto/UpdateBlockRqDto.java
  src/main/java/com/example/want/api/block/service/BlockService.java
Labels: ⭐️ Feat

#26 블록관련 서비스 전~부 수정 완료, (메인 기능들이니 모두 숙지하세요)
  src/main/java/com/example/want/api/block/controller/BlockController.java
  src/main/java/com/example/want/api/block/domain/Block.java
  src/main/java/com/example/want/api/block/dto/BlockActiveListRsDto.java
  src/main/java/com/example/want/api/block/dto/BlockCategoryListRqDto.java
  src/main/java/com/example/want/api/block/repository/BlockRepository.java
  src/main/java/com/example/want/api/block/service/BlockService.java
  src/main/java/com/example/want/api/heart/dto/HeartListResDto.java
Labels: Fix

#31 장소 추가 및 프로젝트 보완
  src/main/java/com/example/want/api/member/domain/Member.java
  src/main/java/com/example/want/api/project/controller/ProjectController.java
  src/main/java/com/example/want/api/project/domain/Project.java
  src/main/java/com/example/want/api/project/dto/ProjectCreateReqDto.java
  src/main/java/com/example/want/api/project/dto/ProjectDetailRsDto.java
  src/main/java/com/example/want/api/project/repository/ProjectRepository.java
  src/main/java/com/example/want/api/project/service/ProjectService.java
  src/main/java/com/example/want/api/projectMember/domain/ProjectMember.java
  src/main/java/com/example/want/api/state/controller/StateController.java
  src/main/java/com/example/want/api/state/domain/State.java
  src/main/java/com/example/want/api/state/dto/CityResDto.java
  src/main/java/com/example/want/api/state/dto/CountryRsDto.java
  src/main/java/com/example/want/api/state/repository/StateRepository.java
  src/main/java/com/example/want/api/state/service/StateService.java
  src/main/resources/static/state.sql
Labels: ⭐️ Feat
